Time::DATE_FORMATS[:datetime] = "%B %d, %Y %I:%M%p"
Time::DATE_FORMATS[:short_datetime] = "%b %d, %Y %I:%M%p"
Time::DATE_FORMATS[:date] = "%B %d, %Y"
Time::DATE_FORMATS[:time] = "%I:%M%p"
Time::DATE_FORMATS[:dateNums] = "%m/%d/%Y"